# Generated by Django 3.2.3 on 2022-04-13 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="attributes",
        ),
        migrations.AddField(
            model_name="mailing",
            name="phone_code",
            field=models.IntegerField(
                blank=True,
                default=1,
                validators=[django.core.validators.MaxValueValidator(999)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailing",
            name="tag",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
