# Generated by Django 3.2.3 on 2022-04-13 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0002_auto_20220413_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="phone_code",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
            ),
        ),
    ]
