# Generated by Django 3.2.3 on 2022-04-13 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0003_alter_mailing_phone_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="timezone",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
            ),
        ),
    ]
