# Generated by Django 3.2.3 on 2022-04-14 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0004_alter_client_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(70000000000),
                    django.core.validators.MaxValueValidator(79999999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="timezone",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
    ]
