# Generated by Django 3.2.3 on 2022-04-14 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0005_auto_20220414_0553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_code",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="timezone",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(12)],
            ),
        ),
    ]
