# Generated by Django 3.2.3 on 2022-04-14 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0006_auto_20220414_0555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="timezone",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-12),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
