# Generated by Django 3.2.3 on 2022-04-14 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0007_alter_client_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_code",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="timezone",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-12),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
