# Generated by Django 3.2.3 on 2022-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0008_auto_20220414_0615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.BooleanField(),
        ),
    ]
