# Generated by Django 3.2.3 on 2022-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0009_alter_message_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
